name = "MatrixAlphaZero"
uuid = "5b242d70-f97d-4fa7-8667-f0513ab0a030"
authors = ["WhiffleFish <tylertronics@gmail.com>"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
MarkovGames = "d061fddc-c47a-4172-865e-fdb23de1c5fa"
TensorGames = "dad72d94-522a-402a-84d3-a630e8ffd4d6"

[compat]
Flux = "0.16.3"
MarkovGames = "0.1.0"
TensorGames = "0.3.9"
