name = "ExperimentTools"
uuid = "7fde32a4-1ade-4293-987a-ae7babf65c50"
version = "0.1.0"
authors = []

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
MarkovGames = "d061fddc-c47a-4172-865e-fdb23de1c5fa"
MatrixAlphaZero = "5b242d70-f97d-4fa7-8667-f0513ab0a030"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SDAGames = "6b0fb67b-fedb-4176-a74d-55c3ed2630ba"
SatelliteDynamics = "0e7c1a32-1b9f-5532-88a4-e668712d6a4c"

[sources]
MarkovGames = {path = "../deps/MarkovGames.jl"}
MatrixAlphaZero = {path = ".."}
SDAGames = {path = "../deps/SDAGames"}
SatelliteDynamics = {path = "../deps/SatelliteDynamics.jl"}

[compat]
ArgParse = "1.2.0"
MarkovGames = "0.2.1"
POMDPTools = "1.1.0"
POMDPs = "1.0.0"
Random = "1.11.0"
